# -*- coding: utf-8 -*-
"""TAREA 3 | OPEN, BYTES, MATRIX, CUT and SAVE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123yFws3-ConO7loQQwRHLzj5uuVXdKok
"""

from PIL import Image      
import matplotlib.pyplot as plt
import numpy as np

files = ['C1','C2','C3','C4']
images = []; img_arr = []

# READ AND SAVE ALL IN A LIST

for i in files:
  images.append(Image.open(i+'.jpg'))
  img_arr.append(np.array(Image.open(i+'.jpg')))

byts = []
for i,j in enumerate(images):
  byts.append(len(j.fp.read()))
  print('El archivo ' + files[i]+'.jpg pesa ',byts[i],' bytes')

for i,j in enumerate(img_arr):
  print('El archivo ' + files[i]+'.jpg pesa ',j.nbytes,' bytes')

for i,j in enumerate(files):
  print(j+" matriz / "+j+".jpg  = ",img_arr[i].nbytes / byts[i] )

centers = []
for i in img_arr:
  y = int(np.shape(i)[0]/2) - 256
  x = int(np.shape(i)[1]/2) - 256
  centers.append(i[y:y+512,x:x+512])

h0 = np.append(centers[0],centers[1],axis=1)
h1 = np.append(centers[2],centers[3],axis=1)
Im5 = np.append(h0,h1,axis=0)

plt.imshow(Im5)
plt.show()

plt.plot(Im5[256,:,0],c='r')
plt.show

plt.plot(Im5[256,:,2])
plt.show

Im5 = Image.fromarray(Im5)   # CONVERTION TO IMAGE OBJECT
Im5.save('Im5.png')
Im5.save('Im5.bmp')
Im5.save('Im5.jpg')

for i in ['Im5.png','Im5.bmp','Im5.jpg']:
  images.append(Image.open(i))            # 4,5,6 index

for i,j in enumerate(['Im5.png','Im5.bmp','Im5.jpg']):
  print('Archivo '+j+' pesa ',len(images[i+4].fp.read()),' bytes')

# MATRIX WHITE

# a = np.full((1024,1024,3), 255) 
# Im5 = Image.fromarray(a.astype(np.uint8), 'RGB')

# im = Image.fromarray(a)  # ARRAY TO IMAGE